### ISSUE TITLE
Syntactic sugar for inline literals

### ISSUE THREAD

**Issue by luisggpina** [daniel-grumberg/varan-div#21]
Implement syntactic sugar for the inline number and string literals.  For instance:
```
read(1027,_,1) => nothing
```
Would expand to something like:
```
read(v1,_,v2) { return v1 == 1027 && v2 == 1; } => nothing
```
Same for string:
```
open("/proc/self/cmdline",_,_) => nothing
```
Would expand to something like:
```
open(v1,_,_) { return !strcmp(v1, "/proc/self/cmdline"); } => nothing
```

The `strcmp` function should be configurable by passing a function pointer the `init` function that compares strings (Varan uses a special one).

**Comment by daniel-grumberg** [comment]
PR is up!
